[package]
name = "ftl"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[workspace]
members = ["./xtask"]

[dependencies]
libc = "0.2"

[features]
unstable = []
# default = ["unstable"]
