[package]
name = "ftl"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[features]
unstable = []
# default = ["unstable"]

[workspace]
members = ["./xtask"]
